FROM openjdk:11-jdk-alpine
MAINTAINER gabrielborjamoscoso
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} nttdataTest-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/nttdataTest-0.0.1-SNAPSHOT.jar"]